POST http://localhost:8000/shorten
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlNTJhYjJiLWMzMGItNDI4Ny05NGNlLTI5NDAzNTA5MWQyYyIsImlhdCI6MTc4MzI4ODQ0NCwiZXhwIjoxNzgzODkzMjQ0fQ.5Y-J1IsVTQbNbaWuhnLg_rlnBKFV476AKVgmG8y1_M8

{
    "url": "https://github.com/sanjudhritlahre",
    "code": "github"
}