POST http://localhost:8000/user/signup
Content-Type: application/json

{
    "firstName": "Sanju",
    "lastName": "Dhritlahre",
    "email": "sanjudhritlahre@example.in",
    "password": "12345678"
}